version: "3.9"

services:
  backend:
    build: ./backend
    container_name: detector-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: detector-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
